name: Upload coverage reports to Codecov

on:
  push:
    branches:
      - main

jobs:
  upload-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
            distribution: 'temurin'
            java-version: '17'

      - name: Build and generate coverage report
        run: ./gradlew koverHtmlReport

      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v4.4.0
        with:
          file: 'coverage_report.xml'
          fail_ci_if_error: true
          verbose: true
        env:
          CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}